=== kristinag9/XML-programming/XML_project/geo_regions.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT regions (region*)>
        <!ELEMENT region (name, note?, situation, relief, borders, area, subregions, climate, soil, flora, fauna)>

        <!ELEMENT name (#PCDATA)>
        <!ELEMENT note (#PCDATA)>
        <!ELEMENT situation (part_of_Bulgaria, note?, districts)>
        <!ELEMENT part_of_Bulgaria (#PCDATA)>
        <!ELEMENT districts (full?, partial)>
        <!ELEMENT full (name+)>
        <!ELEMENT partial (name+)>
        <!ELEMENT relief (mountain, type, average_altitude)>
        <!ELEMENT mountain EMPTY>
        <!ELEMENT average_altitude (#PCDATA)>
        <!ELEMENT type (#PCDATA)>
        <!ELEMENT borders (east, west, north, south)>
        <!ELEMENT east (name, length)>
        <!ELEMENT west (name, length)>
        <!ELEMENT north (name, length)>
        <!ELEMENT south (name, length)>
        <!ELEMENT length (#PCDATA)>
        <!ELEMENT area (percent, size)>
        <!ELEMENT percent (#PCDATA)>
        <!ELEMENT size (#PCDATA)>
        <!ELEMENT subregions (subregion+)>
        <!ELEMENT subregion (name, note?, size, relief)>
        <!ELEMENT climate (note?, type, average_temperature, rain_mode, wind_type)>
        <!ELEMENT average_temperature (#PCDATA)>
        <!ELEMENT rain_mode (#PCDATA)>
        <!ELEMENT wind_type (#PCDATA)>
        <!ELEMENT soil (note?, most_common, other?)>
        <!ELEMENT most_common (#PCDATA)>
        <!ELEMENT other (#PCDATA)>
        <!ELEMENT flora (#PCDATA)>
        <!ELEMENT fauna (#PCDATA)>

        <!ATTLIST region id CDATA #REQUIRED>
        <!ATTLIST mountain has (Да|Не) "Не">
        <!ATTLIST average_altitude metric_units CDATA #REQUIRED>
        <!ATTLIST length metric_units CDATA #REQUIRED>
        <!ATTLIST size metric_units CDATA #REQUIRED>
        <!ATTLIST percent percentage CDATA #REQUIRED>
        <!ATTLIST average_temperature unit CDATA #REQUIRED>

=== kristinag9/XML-programming/XML_project/valid_xml_5.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE regions SYSTEM "geo_regions.dtd">

<regions>
    <region id="6">
        <name>Българско черноморие</name>
        <note>Българското Черноморско крайбрежие представлява една ивица от сушата, разположена на запад от черноморския бряг.</note>
        <situation>
            <part_of_Bulgaria>източна част</part_of_Bulgaria>
            <districts>
                <partial>
                    <name>Добричка</name>
                    <name>Варненска</name>
                    <name>Бургаска</name>
                </partial>
            </districts>
        </situation>
        <relief>
            <mountain has="Не"/>
            <type>предимно равнинен</type>
            <average_altitude metric_units="м">250</average_altitude>
        </relief>
        <borders>
            <east>
                <name>Черно море</name>
                <length metric_units="км">378</length>
            </east>
            <west>
                <name>Дунавска равнина, Старопланинска област,
                    Краищенско-Средногорска област, Тракийско-Странджанска област</name>
                <length metric_units="км">436</length>
            </west>
            <north>
                <name>Румъния</name>
                <length metric_units="км">50</length>
            </north>
            <south>
                <name>Турция</name>
                <length metric_units="км">30</length>
            </south>
        </borders>
        <area>
            <percent percentage="%">2,27</percent>
            <size metric_units="кв.км">31523</size>
        </area>
        <subregions>
            <subregion>
                <name>Северно крайбрежие</name>
                <size metric_units="кв.км">954</size>
                <relief>
                    <mountain has="Не"/>
                    <type>равнинен</type>
                    <average_altitude metric_units="м">71</average_altitude>
                </relief>
            </subregion>
            <subregion>
                <name>Средно крайбрежие</name>
                <size metric_units="кв.км">301</size>
                <relief>
                    <mountain has="Не"/>
                    <type>планински</type>
                    <average_altitude metric_units="м">52</average_altitude>
                </relief>
            </subregion>
            <subregion>
                <name>Южно крайбрежие</name>
                <size metric_units="кв.км">1255</size>
                <relief>
                    <mountain has="Не"/>
                    <type>планинско-котловинен</type>
                    <average_altitude metric_units="м">11</average_altitude>
                </relief>
            </subregion>
        </subregions>
        <climate>
            <note>Българското Черноморско крайбрежие попада в Черноморската климатична област.
                Формирана е под влияние на доминирането на два климатообразуващи фактора – атмосферната циркулация и влиянието на Черно море.
                Има различно проявление на континенталното влияние  (от северозапад и североизток) и средиземноморското (от югозапад).</note>
            <type>черноморски</type>
            <average_temperature unit="Целзий">12,5</average_temperature>
            <rain_mode>Има различия във валежния режим поради различния тип в северната и южната част. </rain_mode>
            <wind_type>северозападен през зимата и североизточен през лятото</wind_type>
        </climate>
        <soil>
            <most_common>черноземни</most_common>
            <other>канелени горски</other>
        </soil>
        <flora>Характерна е евксинската растителност, широколистната горска растителност от средноевропейски тип,
                както и редица растения, водни обитатели.</flora>
        <fauna>Представен е от степни, средноевропейски и средиземноморски видове обитатели.</fauna>
    </region>
</regions>

=== kristinag9/XML-programming/XML_project/valid_xml_4.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE regions SYSTEM "geo_regions.dtd">

<regions>
    <region id="5">
        <name>Рило-Родопска област</name>
        <note>Най-южните части на България са включени в една обща природногеографска област,
            носеща името на двете най-известни планини – най-високата (Рила) и най-голямата по площ (Родопи).</note>
        <situation>
            <part_of_Bulgaria>южната част на България</part_of_Bulgaria>
            <districts>
                <partial>
                    <name>Пернишка</name>
                    <name>Кюстендилска</name>
                    <name>Софийска</name>
                    <name>Пазарджишка</name>
                    <name>Пловдивска</name>
                    <name>Старозагорска</name>
                    <name>Хасковска</name>
                </partial>
            </districts>
        </situation>
        <relief>
            <mountain has="Да"/>
            <type>предимно планински</type>
            <average_altitude metric_units="м">1090</average_altitude>
        </relief>
        <borders>
            <east>
                <name>Тракийско-Странджанска област</name>
                <length metric_units="км">30</length>
            </east>
            <west>
                <name>Македония</name>
                <length metric_units="км">165</length>
            </west>
            <north>
                <name>Краищенско-Средногорска област</name>
                <length metric_units="км">460</length>
            </north>
            <south>
                <name>Гърция</name>
                <length metric_units="км">493</length>
            </south>
        </borders>
        <area>
            <percent percentage="%">18,26</percent>
            <size metric_units="кв.км">31523</size>
        </area>
        <subregions>
            <subregion>
                <name>Осоговско-Беласишката планинска редица и долината на река Струма</name>
                <size metric_units="кв.км">2828</size>
                <relief>
                    <mountain has="Да"/>
                    <type>планински</type>
                    <average_altitude metric_units="м">806</average_altitude>
                </relief>
            </subregion>
            <subregion>
                <name>Рила, Пирин и долината на река Места</name>
                <size metric_units="кв.км">3510</size>
                <relief>
                    <mountain has="Да"/>
                    <type>планински</type>
                    <average_altitude metric_units="м">1260</average_altitude>
                </relief>
            </subregion>
            <subregion>
                <name>Родопи</name>
                <size metric_units="кв.км">13929</size>
                <relief>
                    <mountain has="Да"/>
                    <type>планински</type>
                    <average_altitude metric_units="м">1200</average_altitude>
                </relief>
            </subregion>
        </subregions>
        <climate>
            <note>Променя се от преходно-континентален към континентално-средиземноморски,
                а във височина се видоизменя и придобива чертите на планинския климат.</note>
            <type>преходно-континентален, континентално-средиземноморски и планински</type>
            <average_temperature unit="Целзий">8</average_temperature>
            <rain_mode>Разпределението на валежите по сезони е резултат от средиземноморското влияние</rain_mode>
            <wind_type>западен и северозападен</wind_type>
        </climate>
        <soil>
            <most_common>кафяви горски</most_common>
            <other>планинско-ливадни</other>
        </soil>
        <flora>Поради голямото разнообразие в надморската височина и близостта на средиземноморската област растителността е богата и разнообразна.</flora>
        <fauna>Животинският свят е формиран от представители на средноевропейските и на средиземноморските  животински видове.</fauna>
    </region>
</regions>

=== kristinag9/XML-programming/XML_project/valid_xml_1.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE regions SYSTEM "geo_regions.dtd">

<regions>
    <region id="1">
        <name>Дунавска равнина</name>
        <note>Дунавската равнина е най-голямата природногеографска област на България.</note>
        <situation>
            <part_of_Bulgaria>най-северната част от територията на България</part_of_Bulgaria>
            <note>Обхваща земите непосредствено на юг от река Дунав и между долното течение на река Тимок (на запад) и Черно море (на изток).</note>
            <districts>
                <full>
                    <name>Плевенска</name>
                    <name>Русенска</name>
                    <name>Разградска</name>
                    <name>Силистра</name>
                    <name>Добричка</name>
                </full>
                <partial>
                    <name>Видинска</name>
                    <name>Монтанска</name>
                    <name>Врачанска</name>
                    <name>Ловешка</name>
                    <name>Великотърновска</name>
                    <name>Търговишка</name>
                    <name>Шуменска</name>
                    <name>Варненска</name>
                </partial>
            </districts>
        </situation>
        <relief>
            <mountain has="Не"/>
            <type>низинен</type>
            <average_altitude metric_units="м">178</average_altitude>
        </relief>
        <borders>
            <east>
                <name>Черноморска област</name>
                <length metric_units="км">120</length>
            </east>
            <west>
                <name>Сърбия</name>
                <length metric_units="км">110</length>
            </west>
            <north>
                <name>Румъния</name>
                <length metric_units="км">610</length>
            </north>
            <south>
                <name>Предбалкан</name>
                <length metric_units="км">460</length>
            </south>
        </borders>
        <area>
            <percent percentage="%">28,42</percent>
            <size metric_units="кв.км">31523</size>
        </area>
        <subregions>
            <subregion>
                <name>Западна Дунавска равнина</name>
                <note>Тя е най-ниската част от Дунавската равнина.</note>
                <size metric_units="кв.км">7235</size>
                <relief>
                    <mountain has="Не"/>
                    <type>равнинно-низинен</type>
                    <average_altitude metric_units="м">130</average_altitude>
                </relief>
            </subregion>
            <subregion>
                <name>Средна Дунавска равнина</name>
                <note>Простира се между реките Вит и Янтра.</note>
                <size metric_units="кв.км">4535</size>
                <relief>
                    <mountain has="Не"/>
                    <type>низинно-равнинен</type>
                    <average_altitude metric_units="м">138</average_altitude>
                </relief>
            </subregion>
            <subregion>
                <name>Източна Дунавска равнина</name>
                <note>Заема земите от река Янтра до Черно море. Тя е най-голямата по площ</note>
                <size metric_units="кв.км">19753</size>
                <relief>
                    <mountain has="Не"/>
                    <type>низинно-равнинен</type>
                    <average_altitude metric_units="м">204</average_altitude>
                </relief>
            </subregion>
        </subregions>
        <climate>
            <note>Разположена е в умерения климатичен пояс.</note>
            <type>умерено-континентален</type>
            <average_temperature unit="Целзий">11,5</average_temperature>
            <rain_mode>умереноконтинентален</rain_mode>
            <wind_type>западен и северозападен</wind_type>
        </climate>
        <soil>
            <note>Дунавската равнина е природногеографската област с най-големи площи на плодородни, предимно черноземни, почви.</note>
            <most_common>черноземни</most_common>
            <other>сиви горски</other>
        </soil>
        <flora>Предимно растителни видове, характерни за средноевропейската и за степната растителногеографска област.</flora>
        <fauna>Характерни са евросибирските и европейските видове.</fauna>
    </region>
</regions>

=== kristinag9/XML-programming/XML_project/valid_xml_2.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE regions SYSTEM "geo_regions.dtd">

<regions>
    <region id="3">
        <name>Краищенско-Средногорска област</name>
        <note>Разположена е между Старопланинската област (на север) и Рило-Родопската и Тракийско-Странджанската области (на юг).</note>
        <situation>
            <part_of_Bulgaria>централната част от територията на България</part_of_Bulgaria>
            <districts>
                <partial>
                    <name>Пернишка</name>
                    <name>Кюстендилска</name>
                    <name>Софийска</name>
                    <name>Пазарджишка</name>
                    <name>Пловдивска</name>
                    <name>Старозагорска</name>
                    <name>Ямболска</name>
                    <name>Сливенска</name>
                    <name>Бургаска</name>
                </partial>
            </districts>
        </situation>
        <relief>
            <mountain has="Да"/>
            <type>предимно равнинен</type>
            <average_altitude metric_units="м">547</average_altitude>
        </relief>
        <borders>
            <east>
                <name>Черноморска област</name>
                <length metric_units="км">20</length>
            </east>
            <west>
                <name>Сърбия</name>
                <length metric_units="км">113</length>
            </west>
            <north>
                <name>Старопланинска област</name>
                <length metric_units="км">460</length>
            </north>
            <south>
                <name>Тракийско-Странджанска и Рило-Родопска област</name>
                <length metric_units="км">510</length>
            </south>
        </borders>
        <area>
            <percent percentage="%">12,72</percent>
            <size metric_units="кв.км">31523</size>
        </area>
        <subregions>
            <subregion>
                <name>Задбалкански котловини</name>
                <note>Това е най-северно разположената (по границата със Старопланинската област) подобласт на Краищенско-Средногорската област на България.</note>
                <size metric_units="кв.км">2750</size>
                <relief>
                    <mountain has="Да"/>
                    <type>равнино-ридов</type>
                    <average_altitude metric_units="м">450</average_altitude>
                </relief>
            </subregion>
            <subregion>
                <name>Средногорие</name>
                <note>Средногорието е общо събирателно име на поредица от български планини, последователно подредени във верига с посока на простиране запад-изток.
                    Носи името на Средна гора - най-дългата от тези планини.</note>
                <size metric_units="кв.км">6750</size>
                <relief>
                    <mountain has="Да"/>
                    <type>планинско-хълмист</type>
                    <average_altitude metric_units="м">625</average_altitude>
                </relief>
            </subregion>
            <subregion>
                <name>Краище</name>
                <note>Краището е средната част на Западна България, разположено по границата със Сърбия.</note>
                <size metric_units="кв.км">4620</size>
                <relief>
                    <mountain has="Да"/>
                    <type>планинско-котловинен</type>
                    <average_altitude metric_units="м">565</average_altitude>
                </relief>
            </subregion>
        </subregions>
        <climate>
            <note>Поради мозаечният характер на релефа има голямо разнообразие на климата.
                Налице са проявления на три типа климат. Умерено-континенталният климат е характерен за по-високите котловини
                и по-голямата част от склоновете на ограждащите ги планини.
                В по-ниските и в по-южно разположени котловини има преходно-континентален климат.
                По високите части на планините има проявление планинският климат.</note>
            <type>преходно-континентален</type>
            <average_temperature unit="Целзий">8</average_temperature>
            <rain_mode>Валежите са твърде разнообразни.</rain_mode>
            <wind_type>северозападен</wind_type>
        </climate>
        <soil>
            <most_common>канелени горски</most_common>
            <other>смолници</other>
        </soil>
        <flora>В Средногорието преобладават средноевропейските растителни видове. В Краището е налице етажираност на растителността.</flora>
        <fauna>Животинският свят е представен предимно от евросибирски и средноевропейски видове.</fauna>
    </region>
</regions>

=== kristinag9/XML-programming/XML_project/valid_xml_3.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE regions SYSTEM "geo_regions.dtd">

<regions>
    <region id="4">
        <name>Тракийско-Странджанска област</name>
        <note>Обхваща земите между Родопите, Средногорието и на изток до Българското Черноморско крайбрежие.</note>
        <situation>
            <part_of_Bulgaria>югоизточна част от България</part_of_Bulgaria>
            <districts>
                <partial>
                    <name>Пазарджишка</name>
                    <name>Пловдивска</name>
                    <name>Старозагорска</name>
                    <name>Ямболска</name>
                    <name>Сливенска</name>
                    <name>Бургаска</name>
                </partial>
            </districts>
        </situation>
        <relief>
            <mountain has="Да"/>
            <type>низинен и равнинно-хълмист</type>
            <average_altitude metric_units="м">315</average_altitude>
        </relief>
        <borders>
            <east>
                <name>Черноморска област</name>
                <length metric_units="км">188</length>
            </east>
            <west>
                <name>Краищенско-Средногорска област</name>
                <length metric_units="км">20</length>
            </west>
            <north>
                <name>Същинска Средна гора</name>
                <length metric_units="км">180</length>
            </north>
            <south>
                <name>от Родопите до границата с Гърция и Турция</name>
                <length metric_units="км">429</length>
            </south>
        </borders>
        <area>
            <percent percentage="%">14,95</percent>
            <size metric_units="кв.км">31523</size>
        </area>
        <subregions>
            <subregion>
                <name>Горнотракийска низина</name>
                <note>Тя е най-добре оформената и най-голямата по площ низина в България.</note>
                <size metric_units="кв.км">6030</size>
                <relief>
                    <mountain has="Да"/>
                    <type>предимно низинен</type>
                    <average_altitude metric_units="м">168</average_altitude>
                </relief>
            </subregion>
            <subregion>
                <name>Тунджанска подобласт</name>
                <note>Обхваща земите около долината на река Тунджа в средното и течение. Разположена е източно от Горнотракийската низина.</note>
                <size metric_units="кв.км">5250</size>
                <relief>
                    <mountain has="Да"/>
                    <type>преобладават възвишения и полета</type>
                    <average_altitude metric_units="м">256</average_altitude>
                </relief>
            </subregion>
            <subregion>
                <name>Сакарско-Странджанска подобласт</name>
                <note>Обхваща Сакар, Дервентските възвишения и планината Странджа.</note>
                <size metric_units="кв.км">5308</size>
                <relief>
                    <mountain has="Да"/>
                    <type>планински</type>
                    <average_altitude metric_units="м">520</average_altitude>
                </relief>
            </subregion>
        </subregions>
        <climate>
            <note>Тракийско–Странджанската област се намира на границата между умерения и субтропичния климатичен пояс.</note>
            <type>преходно-континентален</type>
            <average_temperature unit="Целзий">12,25</average_temperature>
            <rain_mode>Валежите се увеличават в посока от запад на изток.</rain_mode>
            <wind_type>западен и северозападен</wind_type>
        </climate>
        <soil>
            <most_common>канелени горски</most_common>
            <other>алувиално-ливадни покрай реките</other>
        </soil>
        <flora>Характерни са растителни видове от средноевропейската и средиземноморската растително-географска област,
            различни видове реликтни растения и ендемити.</flora>
        <fauna>Тук съжителстват евросибирски, средиземноморски и степни видове.</fauna>
    </region>
</regions>

=== kristinag9/XML-programming/XML_project/valid_xml_6.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE regions SYSTEM "geo_regions.dtd">

<regions>
    <region id="2">
        <name>Старопланинска област</name>
        <situation>
            <part_of_Bulgaria>територията между Дунавската равнина и Краищенско-Средногорската природногеографска област и между границата със Сърбия и Черно море</part_of_Bulgaria>
            <districts>
                <partial>
                    <name>Видинска</name>
                    <name>Монтана</name>
                    <name>Врачанска</name>
                    <name>Софийска</name>
                    <name>Ловешка</name>
                    <name>Пловдивска</name>
                    <name>Габровска</name>
                    <name>Старозагорска</name>
                    <name>Великотърновска</name>
                    <name>Сливенска</name>
                    <name>Търговишка</name>
                    <name>Шуменска</name>
                    <name>Бургаска</name>
                    <name>Варненска</name>
                </partial>
            </districts>
        </situation>
        <relief>
            <mountain has="Да"/>
            <type>планински</type>
            <average_altitude metric_units="м">520</average_altitude>
        </relief>
        <borders>
            <east>
                <name>Черноморска област</name>
                <length metric_units="км">50</length>
            </east>
            <west>
                <name>Сърбия</name>
                <length metric_units="км">118</length>
            </west>
            <north>
                <name>Дунавска равнина</name>
                <length metric_units="км">530</length>
            </north>
            <south>
                <name>Краищенско-Средногорска област</name>
                <length metric_units="км">460</length>
            </south>
        </borders>
        <area>
            <percent percentage="%">23,41</percent>
            <size metric_units="кв.км">31523</size>
        </area>
        <subregions>
            <subregion>
                <name>Предбалкан</name>
                <size metric_units="кв.км">14390</size>
                <relief>
                    <mountain has="Да"></mountain>
                    <type>хълмисто-ридов</type>
                    <average_altitude metric_units="м">364</average_altitude>
                </relief>
            </subregion>
            <subregion>
                <name>Главна Старопланинска верига</name>
                <size metric_units="кв.км">11596</size>
                <relief>
                    <mountain has="Да"></mountain>
                    <type>планински</type>
                    <average_altitude metric_units="м">675</average_altitude>
                </relief>
            </subregion>
        </subregions>
        <climate>
            <type>влажен умерено-континентален</type>
            <average_temperature unit="Целзий">10,5</average_temperature>
            <rain_mode>умереноконтинентален</rain_mode>
            <wind_type>западен и северозападен</wind_type>
        </climate>
        <soil>
            <most_common>сиви горски</most_common>
        </soil>
        <flora>Характерните растителни видове са представители на средноевропейската широколистна листопадна растителност.</flora>
        <fauna>Преобладават средноевропейски и евросибирски видове животни.</fauna>
    </region>
</regions>
